### ISSUE TITLE
Forcing the number of clauses?

### ISSUE THREAD

**Issue by hakank** [logic-and-learning-lab/Popper#12]
Is there a way to force that Popper should start with - say - three clauses instead of one? A use case for this is to skip the long road of testing all the 1 and 2 clause programs that I know don't work (since a previous run didn't found any program with just `max_clauses(2)`). 

I assume that this can be done with ASP clauses in `bias.pl`,  but I haven't found out how it's done.

More general, perhaps is would be an idea to have `min_clauses(N)` (as well as `min_vars(N)` and `min_body(N)`)?

**Comment by andrewcropper** [comment]
We can make that change but the performance might be poor.

Popper prunes a lot of the hypothesis space because it first considers smaller programs. If it starts the search from larger programs, then the pruning will likely be poor. We could implement a ‘multi-shot’ Popper, but I am unsure how much demand there is for that use case. 

Furthermore, @rolfmorel is working on an idea where we can prune far more programs. I think we will hold off implementing this feature for now.

**Comment by hakank** [comment]
Thanks for the answer, Andrew.

Making Popper faster would certainly solve much of this.

(Do you want me to close this issue or do you want to keep this as a wish list item?)

**Comment by andrewcropper** [comment]
Closed.
