### ISSUE TITLE
Increasing max_vars results in no solution

### ISSUE THREAD

**Issue by mgualti** [logic-and-learning-lab/Popper#95]
I'm trying to find the solution:

`f(X, Y, Z) :- equal(X, Y), nequal(Y, Z)`

Bias:

```
max_vars(6).
max_body(5).
max_clauses(5).

head_pred(f, 3).
body_pred(equal, 2).
body_pred(nequal, 2).
```

Background:

```
equal(X, Y) :- X = Y.
nequal(X, Y) :- X \= Y.
```

Examples:

```
pos(f(1, 1, 0)).
neg(f(1, 1, 1)).
```

The solution is found when max_vars(5), but when max_vars(6), I get "NO SOLUTION". I run the command with defaults:

`python3 popper.py [folder_name]`

It works if I define `nequal` differently:

```
nequal(1, 0).
nequal(0, 1).
```

But an explicit definition would be large if there were more numbers.

**Comment by andrewcropper** [comment]
Hi,

I think the issue is due to your BK file. If you change the definitions to as follows, it should work.

```
equal(X, X).
nequal(X, Y) :- \+ equal(X,Y).
```

> But an explicit definition would be large if there were more numbers.
That would be large, but if you only have a small domain (<100k), Popper will perform much better if you provide such definitions. In other words, Popper performs much better when learning from ground facts.

Kind regards,

Andrew

p.s. there is no need to provide max_clauses(5). It is ignored unless you are learning recursive programs. Even then, 5 seems high, as 2 rules/clauses is usually sufficient.

**Comment by mgualti** [comment]
Thanks for the clarification. With those definitions for equal and nequal, I get the same result. However, ground facts should work. Just out of curiosity, why do ground facts work better in this case?

**Comment by andrewcropper** [comment]
If the BK is only facts, Popper does some fancy preprocessing on the BK to learn constraints to restrict the hypothesis space, as outlined in this paper: https://arxiv.org/pdf/2202.09806

It is hard to perform this preprocessing if the BK is infinite.

Kind regards,

Andrew
